### PR TITLE
Update Place Wellington

### PR DESCRIPTION
**Pull request by nvkelso**
Updating `data/101/932/275/101932275.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by nvkelso** [comment]
Move NE props and related zoom props from AU record to NZ record, paired with https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/23

**Comment by stepps00** [comment]
LGTM, though iirc the extra carriage returns at the end of records have caused problems with distributions / validation in the past. Changes look good but I'd recommend exportifying the record before merging.

**Comment by stepps00** [comment]
False alarm - it looks like the newer Go exportify tools also add a carriage return at the end of a record. Some recent PRs that have updated WOF records using the Go tools have been merged, none have caused issue.. so tldr: this can be merged as-is.

**Review by stepps00 — APPROVED** [review]
LGTM

**Pull request merged**
