### PR TITLE
Add Yarrabilba locality

### PR DESCRIPTION
**Pull request by stepps00**
Replaces #38 
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/2004

This adds a new record for the locality of Yarrabilba, AU. No PIP work needed, this can be merged as-is.

### CODE REVIEW

**Comment by stepps00** [comment]
@nvkelso this PR adds a new locality in Australia. A refactor of AU admin data is needed to add additional features, but this one-off will fix the case of Yarrabilba.

**Comment by stepps00** [comment]
cc @nvkelso

**Comment by nvkelso** [comment]
Is this a polygon? If so, it'll need to also possibly modify the neighbouring locality polygons else the fabric gets bumpy for revGeo.

**Comment by stepps00** [comment]
This is a polygon addition, but there are no neighbouring locality polygons that need to be adjusted in this case.. eventually, we'll want to update Australia localities/localadmin across the country, but for now I think this single record can be added in to WOF without any additional record updates.

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
