### PR TITLE
[WIP] AUS: admin updates

### PR DESCRIPTION
**Pull request by stepps00**
Work in progress. Will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/1879.

Do not merge.

This PR will eventually replace #10, #14, and #17. Right now, the only commit includes work to flag all existing localadmin records as `is_current` = 0 and deprecated.

@nickstallman - let's build off of this PR as updates to Australia admin records begin. Some "to do" items in Australia, subject to change as we chat through this:

To do:
- [ ] Close out the existing PRs that are open
- [x] Deprecate existing localadmin records
- [ ] Update existing locality records with new geometries, properties, and concordances
- [ ] Add new locality records for missing suburbs
- [ ] Deprecate and supersede any existing "leftover"/non-matching locality records
- [ ] Supersede the existing localadmin coverage into existing (and new) locality coverage that matches the AUS suburb dataset
- [ ] Flag county records with `mz:hierarchy_label` = 1
- [ ] Clean up neighbourhoods as needed. No proposed changes to this placetype at the moment.
- [ ] For map display, to fix the “diminished” text size of locality labels (for @stepps00 to tackle):
  - [ ] Find same named suburb from LGA file, applies the pop_rank of LGA to suburb (to tweak labels and text)
  - [ ] Find same named suburb from SUA file, applies the pop_rank of SUA to suburb (to tweak labels and text)
- [ ] Store vintage ABS concordance ids as needed (all placetypes)
- [ ] Ensure that `lbl:*`, `src:*`, `name:*` properties are updated appropriately
- [ ] Ensure that alt geometries are stored appropriately
- [ ] PIP
- [ ] Validate
- [ ] Add/adjust sources in the `whosonfirst-sources` repo

### CODE REVIEW

**Comment by missinglink** [comment]
Heya, regarding Suburbs (neighborhoods) are they considering in-scope or out-of-scope for this work?

> Clean up neighbourhoods as needed. No proposed changes to this placetype at the moment.

I was hoping we could improve the point-based geoms as per my comment below, and I'm cool with it being either part of this or a separate task, if it's separate I can work on that indepently of this work.

https://github.com/whosonfirst-data/whosonfirst-data/issues/1509#issuecomment-662996671

**Comment by NickStallman** [comment]
@missinglink there's no good government neighbourhood data source currently and no good definition for Australia.

So we'll tackle that after the PSMA data is all up to date and see what we want to do there.

**Comment by NickStallman** [comment]
Oh btw if a "neighbourhood" in WOF is actually a locality in the PSMA dataset then that'll be resolved just by getting the localities fixed up.

**Comment by missinglink** [comment]
I hope not 😱, a 'neighbourhood' is usually the lowest level of the hierarchy, so it should map to 'Suburb' in AUS/NZ terminology.

For example 'Fitzroy' in Melbourne is a Suburb, I guess Manly would also be a Suburb, but I can see how it's not 💯 clear cut..

Here's an example from Pelias I came across today, the venue is [The Australian War Memorial](https://en.wikipedia.org/wiki/Australian_War_Memorial) and it can't be found using the query "The Australian War Memorial, Canberra"

I think it's technically correct to say it's in `Campbell`, Wikipedia describes it as "Campbell is a suburb of Canberra, Australian Capital Territory, Australia. Covering an area to the South East of the central business district".

So in this case I think that `Campbell` should be the `neighbourhood` (and `Canberra` becomes the `locality`)?

Another option is to add `Canberra` as a `localadmin` and leave `Campbell` as a locality? but that seems less correct to me?

As an aside "Pialligo" seems completely wrong here 🤷‍♂️ 

```javascript
"id": "relation/7527080",
"gid": "openstreetmap:venue:relation/7527080",
"layer": "venue",
"source": "openstreetmap",
"source_id": "relation/7527080",
"name": "Australian War Memorial",
"street": "Treloar Crescent",
"confidence": 0.8,
"match_type": "fallback",
"accuracy": "point",
"country": "Australia",
"country_gid": "whosonfirst:country:85632793",
"country_a": "AUS",
"region": "Australian Capital Territory",
"region_gid": "whosonfirst:region:85681493",
"region_a": "ACT",
"localadmin": "Pialligo",
"localadmin_gid": "whosonfirst:localadmin:404550105",
"locality": "Campbell",
"locality_gid": "whosonfirst:locality:101938727",
"continent": "Oceania",
"continent_gid": "whosonfirst:continent:102191583",
"label": "Australian War Memorial, Campbell, ACT, Australia",
"addendum": {
  "osm": {
    "wikidata": "Q782783",
    "wikipedia": "en:Australian War Memorial",
    "website": "https://www.awm.gov.au/",
    "opening_hours": "10:00-17:00; Dec 25 off"
  }
}
```

**Comment by missinglink** [comment]
I think getting the Suburb layer right is essential for geocoding, @NickStallman you mentioned that there's no good data source for neighbourhoods, but the one I linked https://github.com/whosonfirst-data/whosonfirst-data/issues/1509#issuecomment-662996671 seems good to me?

Maybe we're getting our wires crossed a bit and you're thinking of `neighbourhood` as something lower than a Suburb, I'm not aware of any of these, do you possibly have an example?

**Comment by NickStallman** [comment]
Hey @missinglink Canberra certainly isn't a locality, it's a city.
Canberra is a odd example as it skips the LGA/local council layer so it's not great for making decisions on.
Referenece: https://en.wikipedia.org/wiki/Local_government_in_Australia#Australian_Capital_Territory

Yep Pialligo is indeed completely wrong in your example.
It is also missing a County which is where I'd be expecting "Canberra" to appear.
I haven't checked the PSMA data on that one - not sure if Canberra need special workarounds to deal with it's oddities.
If Canberra was the county would that query work correctly?

Current neighbourhoods in WOF are certainly smaller than suburbs (and that layer contains some bizzare data).
The locality and localadmin layers currently are a random mix of suburbs (PSMA locality data).

I did assume neighbourhoods would be like housing estates or campuses or other areas smaller than a suburb.

If we map PSMA localities to neighbourhoods then we end up with the WOF layers of locality and localadmin completely empty?
Since PSMA's Local Government Areas go to county and the very next layer down is PSMA's localities (technically postcodes are in the middle but that's a different topic).

**Comment by missinglink** [comment]
> Hey @missinglink Canberra certainly isn't a locality, it's a city.

I'm so confused 🤯 [London](https://spelunker.whosonfirst.org/id/101750367/), [Paris](https://spelunker.whosonfirst.org/id/1125362873/), [Shanghai](https://spelunker.whosonfirst.org/id/102027181/), [New York](https://spelunker.whosonfirst.org/id/85977539/) and [Tokyo](https://spelunker.whosonfirst.org/id/102031307/) are all Cities and also all on the `locality` layer, your comment sounds like you think that shouldn't be the case?

I wasn't present for the conversations you had with Stephen, so maybe I'm just making things more confused 😆 

As someone who's lived in London, Melbourne and Berlin it's confusing why [Shoreditch London](https://spelunker.whosonfirst.org/id/85790327/) is a `neighbourhood`, [Fitzroy Melbourne](https://spelunker.whosonfirst.org/id/101932939/) is a `locality` and [Prenzlauer Berg](https://spelunker.whosonfirst.org/id/420784283/) is a `neighbourhood`.

I was actually hoping that we could move the Suburbs to the `neighbourhood` layer, but that seems to be an unpopular opinion?

**Comment by missinglink** [comment]
https://en.wikipedia.org/wiki/Suburbs_and_localities_(Australia)

> The Australian usage is closer to the American or British use of "district" or "neighbourhood", and can be used to refer to any portion of a city.

**Comment by missinglink** [comment]
Okay so I just spent way too long looking at this again and I think I understand it now.

It looks like the decision from the WOF team was the greater Melbourne Area (for example) is defined as a `macrocounty` and then Suburbs are considered subdivisions of that, so they each become a `locality`, whether they have [their own municipal status](https://en.wikipedia.org/wiki/Fitzroy,_Victoria) or [not](https://en.wikipedia.org/wiki/Collingwood,_Victoria).

The CBD (central business district) is considered a suburb and so also becomes a very small `locality` at the heart of the `county`, then as you walk out from the city, every 5 mins walk you enter a new `locality`.

This is very different from how London, New York, Berlin etc. are divided, where you may cross over neighbourhoods within a 5 minute walk and maybe even a borough border but changing localities generally takes a car trip.

So sorry about the noise, this is probably technically correct, but the terminology is very different from what the person on the street would use, in particular what they would not normally call their 'city' a 'macrocounty' or 'county'.

**Comment by missinglink** [comment]
Okay I have to stop reading, it's only making me more and more confused ;)
- https://en.wikipedia.org/wiki/Cadastral_divisions_of_Victoria
- https://en.wikipedia.org/wiki/County_of_Bourke,_Victoria

**Comment by NickStallman** [comment]
@missinglink haha this kind of thing is fun isn't it? :)

In Australia most cities have a city (macrocounty) and a suburb with the exact same name which refers to the CBD as you say.
The CBD is indeed tiny so when someone says "Sydney" they almost certainly aren't referring to the suburb (you'd say I'm going in to the city or CBD instead).

How does this stuff compare to OSM's admin layer chart?
https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#National
It doesn't include macrocounty, but otherwise it looks good for Australia (including our postcode quirks).

**Comment by stepps00** [comment]
@NickStallman @missinglink there hasn't been much traction on AUS updates + there have been recent data edits in this repo that have caused merge conflicts. I'm going to close this PR, but happy to re-open a new PR when we begin updates again.

**Pull request closed without merging**
